"""Option pricing and hold-time analytics for long single-leg positions."""

from .greeks import Greeks, black_scholes, expected_move, implied_vol
from .probability import finish_probability, touch_probability
from .decay import (
    DropDead,
    Recovery,
    breakeven_spot,
    decay_schedule,
    drop_dead,
    hurdle_ratio,
    recovery,
    shot_clock,
)
from .checks import (
    FAIL,
    PASS,
    UNKNOWN,
    Check,
    check_delta,
    check_dte,
    check_earnings,
    check_hurdle,
    check_iv_rank,
    check_size,
    check_spread,
    check_target,
    run_all,
    verdict,
)

__all__ = [
    "Greeks",
    "black_scholes",
    "expected_move",
    "implied_vol",
    "finish_probability",
    "touch_probability",
    "Recovery",
    "DropDead",
    "hurdle_ratio",
    "breakeven_spot",
    "recovery",
    "drop_dead",
    "decay_schedule",
    "shot_clock",
    "Check",
    "PASS",
    "FAIL",
    "UNKNOWN",
    "check_size",
    "check_dte",
    "check_delta",
    "check_hurdle",
    "check_iv_rank",
    "check_spread",
    "check_earnings",
    "check_target",
    "run_all",
    "verdict",
]
